### ISSUE TITLE
Does the API daily limit apply also for the GET document endpoint?

### ISSUE THREAD

**Issue by sduran-contrast** [amzn/amazon-hub-counter-api-docs#19]
> Partners can send a maximum number of 15 API calls per day. If there is a specific business case for the Partner to perform more than 15 calls a day, please contact your Amazon representative to approve a temporary limit increase.

I'm interested in consuming the **Return a document** endpoint by applying a Polling strategy in order to verify what's the status of the Access Point Locations I posted, is this possible? or the 15 days limit applies for all the endpoints and not just the "Create a feed" endpoint?

**Comment by korbiniw** [comment]
The limits of 15 feeds per day only applies to the POST (Create a feed) endpoint. The GET requests are not impacted.
